### ISSUE TITLE
crash on no input, just hit enter

### ISSUE THREAD

**Issue by robertbrandt** [jacksteel5314/RomanNumeralFinal#11]
```
(romannum_venv) brndt@penguin:~/dev/RomanNumeralFinal$ python RomanNumeralConverter && cat Results.txt 
Welcome to the Roman Numeral Converter
Input a Roman Numeral or Number: 

Traceback (most recent call last):
  File "/home/brndt/dev/RomanNumeralFinal/RomanNumeralConverter", line 40, in <module>
    main()
  File "/home/brndt/dev/RomanNumeralFinal/RomanNumeralConverter", line 13, in main
    valid_entry = roman_nums.valid_entry_f(value)
  File "/home/brndt/dev/RomanNumeralFinal/roman_numerals_lib.py", line 46, in valid_entry_f
    if value[0].isnumeric():
IndexError: string index out of range
(romannum_venv) brndt@penguin:~/dev/RomanNumeralFinal$
```

**Comment by robertbrandt** [comment]
Fixed with f190a500c30093bf71899ea2009a7a501f1b4b7f
