### ISSUE TITLE
crash on input of 4000

### ISSUE THREAD

**Issue by robertbrandt** [jacksteel5314/RomanNumeralFinal#12]
```
(romannum_venv) brndt@penguin:~/dev/RomanNumeralFinal$ python RomanNumeralConverter && cat Results.txt 
Welcome to the Roman Numeral Converter
Input a Roman Numeral or Number: 
4000
Traceback (most recent call last):
  File "/home/brndt/dev/RomanNumeralFinal/RomanNumeralConverter", line 40, in <module>
    main()
  File "/home/brndt/dev/RomanNumeralFinal/RomanNumeralConverter", line 22, in main
    conversion = roman_nums.numerical(value)
  File "/home/brndt/dev/RomanNumeralFinal/roman_numerals_lib.py", line 33, in numerical
    roman_numeral = dict_num.get(multiplier) + dict_num.get((i+1) * multiplier) + roman_numeral
TypeError: can only concatenate str (not "NoneType") to str
(romannum_venv) brndt@penguin:~/dev/RomanNumeralFinal$
```

**Comment by robertbrandt** [comment]
Fixed with f190a500c30093bf71899ea2009a7a501f1b4b7f
